{% set version = "2.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-s2dv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/s2dv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/s2dv/s2dv_{{ version }}.tar.gz
  sha256: 7909f65aceafe8c46e7bd6eb704246b1a7ff0289a977ae437e4fcdbd020f2798

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-climprojdiags
    - r-nbclust
    - r-specsverification >=0.5.0
    - r-abind
    - r-bigmemory
    - r-easyncdf
    - r-easyverification
    - r-mapproj
    - r-maps
    - r-multiapply >=2.1.1
    - r-ncdf4
    - r-plyr
    - r-signal
    - r-zoo
  run:
    - r-base
    - r-climprojdiags
    - r-nbclust
    - r-specsverification >=0.5.0
    - r-abind
    - r-bigmemory
    - r-easyncdf
    - r-easyverification
    - r-mapproj
    - r-maps
    - r-multiapply >=2.1.1
    - r-ncdf4
    - r-plyr
    - r-signal
    - r-zoo

test:
  commands:
    - $R -e "library('s2dv')"           # [not win]
    - "\"%R%\" -e \"library('s2dv')\""  # [win]

about:
  home: https://earth.bsc.es/gitlab/es/s2dv/
  license: GPL-3.0-only
  summary: An advanced version of package 's2dverification'. Intended for seasonal to decadal
    (s2d) climate forecast verification, but also applicable to other types of forecasts
    or general climate analysis. This package is specifically designed for comparing
    experimental and observational datasets. It provides functionality for data retrieval,
    post-processing, skill score computation against observations, and visualization.
    Compared to 's2dverification', 's2dv' is more compatible with the package 'startR',
    able to use multiple cores for computation and handle multi-dimensional arrays with
    a higher flexibility. The Climate Data Operators (CDO) version used in development
    is 1.9.8. Implements methods described in Wilks (2011) <doi:10.1016/B978-0-12-385022-5.00008-7>,
    DelSole and Tippett (2016) <doi:10.1175/MWR-D-15-0218.1>, Kharin et al. (2012) <doi:10.1029/2012GL052647>,
    Doblas-Reyes et al. (2003) <doi:10.1007/s00382-003-0350-4>.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
