{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-s2dv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/s2dv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/s2dv/s2dv_{{ version }}.tar.gz
  sha256: 3d7d13ea001742227d3759d7b4e0eabff4d01d8581666ff17b1ac3fbc26af351

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-climprojdiags
    - r-nbclust
    - r-specsverification >=0.5.0
    - r-abind
    - r-bigmemory
    - r-easyncdf
    - r-easyverification
    - r-mapproj
    - r-maps
    - r-multiapply >=2.1.1
    - r-ncdf4
    - r-plyr
  run:
    - r-base
    - r-climprojdiags
    - r-nbclust
    - r-specsverification >=0.5.0
    - r-abind
    - r-bigmemory
    - r-easyncdf
    - r-easyverification
    - r-mapproj
    - r-maps
    - r-multiapply >=2.1.1
    - r-ncdf4
    - r-plyr

test:
  commands:
    - $R -e "library('s2dv')"           # [not win]
    - "\"%R%\" -e \"library('s2dv')\""  # [win]

about:
  home: https://earth.bsc.es/gitlab/es/s2dv/
  license: GPL-3.0-only
  summary: The advanced version of package 's2dverification'. It is intended for 'seasonal to decadal' (s2d) climate forecast verification, but it can also be used in other kinds of forecasts or general climate analysis. This package is specially designed for the comparison between the experimental and observational datasets.
    The functionality of the included functions covers from data retrieval, data post-processing, skill scores against observation, to visualization. Compared to 's2dverification', 's2dv' is more compatible with the package 'startR', able to use multiple cores for computation and handle multi-dimensional arrays with a higher
    flexibility.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
